### ISSUE TITLE
code run error 

### ISSUE THREAD

**Issue by shliujing** [zwd2016/TG-LSTM-network-for-time-series-prediction#1]
Hi, could you tell me that what the versin of TensorFlow and Keras are? I always failling to run code, or can you provide Docker version of the running environment support, thank a lot!

```
2021-06-10 20:38:05.509245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-10 20:38:05.509417: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:/Users/LIU/Nextcloud/code/ad/TG-LSTM-network-for-time-series-prediction/TG-LSTM.py", line 11, in <module>
    from keras.layers import Dense
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\utils\__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\utils\multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\layers\__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\__init__.py", line 3, in <module>
    from .input_layer import Input
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\input_layer.py", line 7, in <module>
    from .base_layer import Layer
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\base_layer.py", line 12, in <module>
    from .. import initializers
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

**Comment by zwd2016** [comment]
Hi,
Sorry for the late reply to your question.
I recommend you use TensorFlow=1.14 and keras=2.1.5 !
Best regards,
Wendong
Apr. 23, 2022

**Comment by zwd2016** [comment]
> Hi, could you tell me that what the versin of TensorFlow and Keras are? I always failling to run code, or can you provide Docker version of the running environment support, thank a lot!
> 
> ```
> 2021-06-10 20:38:05.509245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2021-06-10 20:38:05.509417: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Traceback (most recent call last):
>   File "C:/Users/LIU/Nextcloud/code/ad/TG-LSTM-network-for-time-series-prediction/TG-LSTM.py", line 11, in <module>
>     from keras.layers import Dense
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\__init__.py", line 3, in <module>
>     from . import utils
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\utils\__init__.py", line 27, in <module>
>     from .multi_gpu_utils import multi_gpu_model
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\utils\multi_gpu_utils.py", line 7, in <module>
>     from ..layers.merge import concatenate
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\layers\__init__.py", line 4, in <module>
>     from ..engine.base_layer import Layer
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\__init__.py", line 3, in <module>
>     from .input_layer import Input
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\input_layer.py", line 7, in <module>
>     from .base_layer import Layer
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\engine\base_layer.py", line 12, in <module>
>     from .. import initializers
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
>     populate_deserializable_objects()
>   File "D:\Tools\Anaconda\envs\hw-kpi\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
>     generic_utils.populate_dict_with_module_objects(
> AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
> ```
Hi,
Sorry for the late reply to your question.
I recommend you use TensorFlow=1.14 and keras=2.1.5 !
Best regards,
Wendong
Apr. 23, 2022
